version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: erp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=college_erp
      - POSTGRES_USER=erp_user
      - POSTGRES_PASSWORD=erp_password
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: erp_web
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=college_erp
      - DB_USER=erp_user
      - DB_PASSWORD=erp_password
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-prod-college-erp-system-key-2026
      - DEBUG=True
    depends_on:
      - db

volumes:
  postgres_data:
